id: P000376
initial_creation_type: ocr
created_at: 17/03/2020
last_modified_at: 2021-12-16 15:36:46.933258
source_metadata:
  id: bdr:W1PD90005
  title: སྡེ་རོང་རྫོང་གི་ལོ་རྒྱུས་དེབ་ཐེར།
  author: ''
  volumes:
    3e47a6c2ffb64242a6500f363ab2a33a:
      image_group_id: I1PD90055
      title: Volume 1 of de rong xian zhi
      volume_number: 1
      total_pages: 536
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
